### ISSUE TITLE
2019.3.x Support?

### ISSUE THREAD

**Issue by hhu-mahmoud** [CSharpAnalyzers/ExceptionalReSharper#98]

**Comment by ManticSic** [comment]
I will provide a version supporting 2019.3.1 as soon as possible.
But sadly I cannot publish it to the jetbrains plugin repository till @RicoSuter give me access to the plugin.

**Comment by ManticSic** [comment]
Done, see #100

**Comment by hhu-mahmoud** [comment]
@ManticSic it still not exists in Extenstion Manager!! is there any new SDK update ?

**Comment by hhu-mahmoud** [comment]
@ManticSic Thanks, then we will wait for pushing to JetBrains repo
